// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWEPMLTndxIE69zz3jp_o2ekWS6iIy5aw',
    appId: '1:168597634962:web:5acecf96b9326e8a88cb4b',
    messagingSenderId: '168597634962',
    projectId: 'task-manager-52b19',
    authDomain: 'task-manager-52b19.firebaseapp.com',
    storageBucket: 'task-manager-52b19.appspot.com',
    measurementId: 'G-ZX164NJCNH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi-S4wqHCEyfgL4GD1_KswB75svaqGvg4',
    appId: '1:168597634962:android:7319e66b67babbe388cb4b',
    messagingSenderId: '168597634962',
    projectId: 'task-manager-52b19',
    storageBucket: 'task-manager-52b19.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAt-i1pV9TLScUCpj-nygwANCj2jeAu8BU',
    appId: '1:168597634962:ios:ebd54df5771dd6f888cb4b',
    messagingSenderId: '168597634962',
    projectId: 'task-manager-52b19',
    storageBucket: 'task-manager-52b19.appspot.com',
    iosBundleId: 'com.example.taskMangemant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAt-i1pV9TLScUCpj-nygwANCj2jeAu8BU',
    appId: '1:168597634962:ios:354241c72471e02788cb4b',
    messagingSenderId: '168597634962',
    projectId: 'task-manager-52b19',
    storageBucket: 'task-manager-52b19.appspot.com',
    iosBundleId: 'com.example.taskMangemant.RunnerTests',
  );
}
